name: Linting & e2e tests (disabled)

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # just perform install
          runTests: false
      - name: Lint with ESLint
        run: yarn lint
      # Disabled? tests are not up to date...
      # - name: Run e2e tests
      #   uses: cypress-io/github-action@v6
      #   with:
      #     # we have already installed all dependencies above
      #     install: false
      #     # run server in the background
      #     start: yarn dev
